name: klarto
description: Todo-list app for all.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  image_picker: ^1.0.4
  http_parser: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/add-square.svg
    - assets/icons/edit.svg
    - assets/icons/heart.svg
    - assets/icons/link.svg
    - assets/icons/three-dots.svg
    - assets/icons/trash.svg
    - assets/icons/check.svg
    - assets/icons/close.svg
    - assets/icons/arrow-left.svg
    - assets/icons/arrow-right.svg
    - assets/icons/calendar-2.svg
    - assets/icons/refresh.svg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_24pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_24pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_24pt-BoldItalic.ttf
          weight: 700
          style: italic